name: EliteShop CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: elite-shop
  ACR_NAME: eliteshop.azurecr.io
  GITOPS_REPO: https://github.com/skr0hit/Microservice_Based_E-commerce_application_full_DevOps_implemented.git
  GITOPS_BRANCH: main
  GITOPS_PATH: k8s/deployment.yaml
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: ⬇ Checkout Application Code
        uses: actions/checkout@v4

      - name: 🧪 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🔐 Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 🔁 Patch & Push GitOps Deployment File
        env:
          GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        run: |
          sed -i "s|image: .*|image: ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|" ${{ env.GITOPS_PATH }}
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.GITOPS_PATH }}
          git commit -m "Update EliteShop image to ${{ env.IMAGE_TAG }}"
          git push https://${{ secrets.GITOPS_TOKEN }}@github.com/skr0hit/Microservice_Based_E-commerce_application_full_DevOps_implemented.git HEAD:${{ env.GITOPS_BRANCH }}
      
      - name: 🎉 Done
        run: echo "Image pushed & GitOps repo updated. Argo CD will take it from here!"